on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: .

jobs:
  check-properties:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: bundle install

      - name: Check properties
        working-directory: ./tax-sales
        run: ./bot.rb
