on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: .

jobs:
  check-properties:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - run: bundle install

      - name: Check properties
        working-directory: ./tax-sales
        run: ./bot.rb

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.csv *.pdf
          git commit -a -m "[bot] Listings Changed"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        if: ${{ hashFiles('tax-sales/email_sentinel') != '' }}
        with:
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # This connection uses TLS (default is true if server_port is 465)
          secure: true
          # mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: "4440: New Listings"
          # Required recipients' addresses:
          to: steven@deobald.ca,preethi@deobald.ca
          # Required sender full name (address can be skipped):
          from: 4440 Tax Sales Bot
          # Optional plain body:
          body: Some new tax sale listings were found in ${{github.repository}}!
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: ./tax-sales/listings.csv,./tax-sales/listings.pdf
