on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  check-properties:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tax-sales
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Check properties
        run: ./bot.rb
