on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: .

jobs:
  check-properties:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: bundle install

      - name: Check properties
        working-directory: ./tax-sales
        run: ./bot.rb

      - name: config email
        run: git config user.email "steven@ffffs.org"
      - name: config username
        run: git config user.name "GitHub Actions"
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh_repo }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "commit new PIDs and PDFs"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
