on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: .

jobs:
  check-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Check properties
        working-directory: ./tax-sales
        run: ./bot.rb
